### ISSUE TITLE
clicking "JabbR" in the top left corner should redirect to the home screen

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#1]

**Comment by heatherbshapiro** [comment]
Updated it to redirect to home page on click. 

```
<div class="banner" role="banner">
                <h1><a href="#">JabbR</a></h1>
 </div>
```

**Comment by JamesEarle** [comment]
Changed from `<a href="#">` to `<a href="/">` to always redirect to root when you click JabbR. The use of `#` only forces the page to scroll to the top, not actually redirect. Pushing this change directly on `dev`

:shipit:
