### ISSUE TITLE
Refactor JabbR-Core files to work with the new models

### ISSUE THREAD

**Issue by jcocchi** [MachUpskillingFY17/JabbR-Core#100]
-Ensure all files are using the new models from the JabbR-Core.Data package
-Make sure the naming of properties is consistent with the new models
-Make sure the "join" collections are functioning properly (ex. AllowedRooms used to be a collection of ChatRooms, now it is a collection of ChatRoomChatUserAllowed objects, which each contain a room and a user object)

**Comment by KSLHacks** [comment]
@jcocchi Once we get the basic chatroom functionality. I can help integrate if you need.
