### ISSUE TITLE
Missing icons in top right nav bar

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#108]
These icons got nerfed somewhere in the EF or SignalR work, they were visible on my testing branch but missing on @jcocchi's branch, as well as here on `Heather-Kevin/chatroom` ![missing icons](https://cloud.githubusercontent.com/assets/5976499/18806543/15fd037c-81e5-11e6-89fd-495713063db2.PNG)

**Comment by adamtuliper** [comment]
@ashanhol any chance related to work on bundling? Whats browser show in f12 tools? (or fiddler)

**Comment by JamesEarle** [comment]
resolved in #110
