### ISSUE TITLE
"Cannot read property 'client' of undefined" in Chat.js: 298

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#11]
Raised when `chat.client.joinRoom = function (room) { ... }` is called. The chat variable is undefined for some reason, so we need to look into the parameters that are passed to it and ensure they are all not `null`

**Comment by JamesEarle** [comment]
At the beginning of the file, you'll see `var chat = connection.chat, ...`.

In this context, `connection.chat` is passed from the function parameter, and is actually `window.jQuery.connection`, or just `$.connection`.

There is no chat value associated with `$.connection`, so `var chat` is `null`. This is possibly due to no SignalR support yet? The hubs may be responsible for setting this up.

**Comment by JamesEarle** [comment]
[This StackOverflow post has some insight.](http://stackoverflow.com/questions/12396233/connection-is-undefined-signalr-0-5-3-mvc4)

**Comment by adamtuliper** [comment]
Hang tight on this one until the working SignalR bits are installed and
tested
https://github.com/MachUpskillingFY17/JabbR-Core/issues/3#issuecomment-243003900

**Comment by JamesEarle** [comment]
This has been resolved by Kevin and Heather's work on SignalR. Most recent work in PR #37, issue #31
