### ISSUE TITLE
Implement Create Room (Button + Command)

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#111]
- Be able to create a new room via the button in the Lobby view.
- Be able to create a new room using the /create command.
- Be able to re-join the newly created room without null errors.

Currently. You can create a room via button. But you can not add messages to chat due to exception.
Probably must create a new ChatRoom object and add to InMemoryRepo.
```
if (room == null)
{
     throw new HubException String.Format(LanguageResources.RoomMemberButNotExists, roomName);
}
```

Currently. /create <roomName> command works with the same issues as the button. (This is because the button invokes "/create <roomName>" behind the scenes.. Fixing one should fix the other).

**Comment by JamesEarle** [comment]
This is done. We can't message yet due to #113 but I'll work on that next.
