### ISSUE TITLE
Implement Leave Room ('x' Tab + Command)

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#112]
- Be able to leave the current room without errors.

Current error:
"Object reference not set to an instance of an object."
```
public static void Remove UserInRoom(this ICache cache, ChatUser user, ChatRoom room)
{
     cache.Remove(CacheKeys.GetUserInRoom(user, room));
}
```

**Comment by JamesEarle** [comment]
@heatherbshapiro you've completed this, so I'm closing the issue.

**Comment by KSLHacks** [comment]
@JamesEarle I would leave them open for the individuals to close, especially since we're waiting for the PR to go through.
