### ISSUE TITLE
Figure out why events aren't triggering in da hub

### ISSUE THREAD

**Issue by heatherbshapiro** [MachUpskillingFY17/JabbR-Core#122]
Currently, we have to explicitly trigger the events in chat.cs. We called logon and joinroom to make them work. Old jabbr doesn't have this, so we need to figure out why this is happening and if we are missing anything.

**Comment by JamesEarle** [comment]
i think in old JabbR when you're authenticated correctly SignalR calls a bunch of different things behind the scenes, including the events that would trigger things like this behind the scenes... Would be a good question to bring when we go to Redmond again.

**Comment by JamesEarle** [comment]
I have to make an explicit call `Clients.Caller.userNameChanged(user);` in Join, and Heather makes an explicit call in `Clients.Caller.leave(userViewModel, room.Name);` for Leave.

I'll create an issue for Heather's, mine is currently #129 we can't forget to revert these changes.

**Comment by JamesEarle** [comment]
Tracking heather's in issue #148

**Comment by adamtuliper** [comment]
We have more explicit ones. Voting to close. Doh. Everyone just voted. Closing.
