### ISSUE TITLE
Write tests for Chat.cs

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#123]
Working in Justine/persistedRepository to write basic function tests which incorporate the data models.
Expect to find some blockers along the way to correct which will hopefully smooth the transition with the most updated chat.cs working on SingalR (Heather-Kevin/chatroom)

**Comment by KSLHacks** [comment]
Having issues testing Chat.cs due to objects not being initialized by the Hub's pipeline. Hub's properties are protected so new instances of the objects must be created by itself, not explicitly.

**Comment by JamesEarle** [comment]
@KSLHacks I got this working without dependency injection. I'm working on branch `james/test-startup` right now. I'm going to write a few extra tests since the current ones are passing too. I'll open a PR by the end of today

**Comment by JamesEarle** [comment]
I'm able to execute some Chat commands via tests, but not all of them. An example is `LoadRooms`,

this is because of the issue you've described with the Chat pipeline and SignalR.

![Screenshot of Chat pipeline error](https://cloud.githubusercontent.com/assets/5976499/19009374/1abf7c58-8728-11e6-94fe-c7a0d4329e9d.png)

**Comment by KSLHacks** [comment]
@JamesEarle sounds good. I'll hop on your branch in a bit and check it out.

**Comment by JamesEarle** [comment]
@KSLHacks as an update, anything that calls Clients will throw this exception, and in addition the `Context` variable is null (because Hubs instantiate it behind the scenes)

Any methods that use either of those won't work from the test.

**Comment by KSLHacks** [comment]
@JamesEarle That's exactly the issue I'm seeing. Good to see we're getting the same null and exceptions.

**Comment by JamesEarle** [comment]
@KSLHacks I got this working earlier today. You're now able to spoof the Chat hub correctly, so I'm voting to close this issue once I open up a PR and get the changes merged 👍

**Comment by KSLHacks** [comment]
Current tests pass - merged into dev. Included in v0.3
