### ISSUE TITLE
Create abstraction layer between dependency injected services and Chat hub

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#124]
The `Chat` hub gets renewed every time long polling refreshes (multiple times a second), and as a result used to be creating a `new InMemoryRepository` every time. With dependency injection, we can pass a Singleton reference of an `IJabbrRepository` that is bound to `InMemoryRepository`.

This approach is going to create problems with asynchronous actions in the future because Entity Framework isn't thread safe. We can create an abstraction layer between `Chat` and where the bindings occur inside `Startup.cs` to mimic the way binding occurs with NInject. We can do this by making the binds in `Startup.cs`, and then making the initial requests for the concrete implementations of the inject interface, and passing around those references via the intermediate abstraction class.

This is the code from original JabbR whose data flow we want to mimic.
```
kernel.Bind<IJabbrRepository>()
                .To<PersistedRepository>();
//...
kernel.Bind<Chat>()
                  .ToMethod(context =>
                  {
                      var resourceProcessor = context.Kernel.Get<ContentProviderProcessor>();
                      var recentMessageCache = context.Kernel.Get<IRecentMessageCache>();
                      var repository = context.Kernel.Get<IJabbrRepository>();
                      var cache = context.Kernel.Get<ICache>();
                      var logger = context.Kernel.Get<ILogger>();
                      var settings = context.Kernel.Get<ApplicationSettings>();

                      var service = new ChatService(cache, recentMessageCache, repository, settings);

                      return new Chat(resourceProcessor,
                                      service,
                                      recentMessageCache,
                                      repository,
                                      cache,
                                      logger,
                                      settings);
                  });
```

**Comment by JamesEarle** [comment]
Investigating setting up the native InMemoryDatabase in .NET Core, so this may not be necessary. Will investigate further.

**Comment by JamesEarle** [comment]
This won't be necessary if we can have the InMemory database working natively in .NET Core. Closing.

**Comment by adamtuliper** [comment]
Thoughts on keeping this open to document behavior here for DI - so we can
ensure this is happening the same way (and sharing repository) with chat
and chatservice?

**Comment by JamesEarle** [comment]
@adamtuliper sure thing, I'll reopen. We can use this issue to track the DI and native InMemory database progress, alongside the additional (more specific) bug issues I've got posted for that.

**Comment by adamtuliper** [comment]
As per David, we can do everything out of the box with DI in .NET Core. We'll create another issue to track that.
