### ISSUE TITLE
.NET Core In Memory database error with JabbrContext

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#125]
I was trying to fix #124 by swapping out our InMemoryRepository for an InMemory database that's provided by .NET Core natively. My thoughts were that this would allow us to use dependency injection to pass around the database context and use that throughout the lifecycle of the application (instead of manually adding our own singleton repository). 

Whenever I try to instantiate an instance of the JabbrContext I receive this error though.

![System.TypeLoadException](https://cloud.githubusercontent.com/assets/5976499/18926769/fd256eca-856d-11e6-9c1f-d38643ebdedd.png)

And it says in the error message that `Microsoft.EntityFrameworkCore.InMemory does not have an implementation`

**Comment by adamtuliper** [comment]
Just FYI - in-mem database is def something we want  (its what Justine and I were discussing last time I was in office on the whiteboard as the next steps for InMemRepository). The intent is that this will replace the inmemory repository list implementation, but only after we have something working everything else can go against for the rest of the code.

**Comment by adamtuliper** [comment]
Diego from EF team says try
.ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning))
James reports same error.

**Comment by JamesEarle** [comment]
@adamtuliper yes I was working on this with Justine when she was trying to do some testing. She hits the exact same error when using EntityFramework Core to setup a DB in the repository. We'll work on this with the EF team next week

**Comment by adamtuliper** [comment]
Changed code as per EF team by using

services.AddScoped<InMemoryTransactionManager, TestInMemoryTransactionManager>();

Prior to

services.AddEntityFrameworkInMemoryDatabase()
    .AddDbContext<JabbrContext>((serviceProvider, options) =>
    {
        options
        .UseInternalServiceProvider(serviceProvider)
        .UseInMemoryDatabase();
    });
