### ISSUE TITLE
explore caching

### ISSUE THREAD

**Issue by heatherbshapiro** [MachUpskillingFY17/JabbR-Core#134]
Look into what caches we need, where, and how to implement them. Several of the commands use them as well.

**Comment by adamtuliper** [comment]
We need working (1.) RecentMessageCache which is a wrapper around (2.) RoomCache, which holds the messages per room.  There's (3.) ICache, which is a just a general MemoryCache thats used by the ChatService (and exended via CacheExtensions and RepositoryExtensions - the only operations are to Get, IsUserInRoom, SetUserInRoom, RemoveUserInRoom).  There's a private (4.)_commandCache, but that should work as of everyone's latest pulls.  Added appropriate ones in #38
