### ISSUE TITLE
Validate / Implement RecentMessageCache

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#136]
Need to understand if RecentMessageCache is implemented and working correctly. 
This is used in Chat and ChatService. This has a dependency on RoomCache so that will need to be verified as part of this.

**Comment by ashanhol** [comment]
Update: waiting until justine/persisterrepository is merged as it has a lot of changes. In the meantime, found two places where  room.ChatMessages.Add(chatMessage); was being updated both in chat.cs and chatService.cs. 
Need to look into how it's actually being used as Heather mentioned they had implemented RecentMessageCache as a list.

**Comment by ashanhol** [comment]
Added David Fowler's tests "GetRecentMessagesReturnsTheLastNMessages" and "ThreadSafety". Both pass. 
After stepping through both old and new Jabbr, I see that old Jabbr's RecentMessageCache doesn't seem to cache messages effectively- in ChatService.cs, `_recentMessageCache.Add(chatMessage);` uses NoopCache in RecentMessageCache.cs, which is empty. Regardless, when you load up an old room it pulls messages from the database, which we don't have working in Jabbr core. Once that's working messages should be cached.

**Comment by ashanhol** [comment]
UPDATE: David Fowler said don't use RecentMessageCache in Jabbr-Core. He said to forget it for now. 
Todo: remove the code for RecentMessageCache.
