### ISSUE TITLE
Multiple @using statements in partial templates

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#14]
Not sure if this will present a performance issue or not, because it may be pointing to the libraries more than once when the `@Html.Partial` calls are made. 

A possible resolution would be taking every template that requires the `@using` statement and putting them together in a single file, but this adds complexity when editing these templates.

**Comment by adamtuliper** [comment]
@using is simply a compiler help, this should be minimal for compilation.
It tells the compiler what namespaces are ok to seach in to find types for
compilation. Once compiled, its of no concern.

**Comment by JamesEarle** [comment]
Got it 👍 will close.

**Comment by gcrev93** [comment]
wooo go James!
