### ISSUE TITLE
Ambiguity exists between "JabbR_Core.Models" and "JabbR_Core.Data.Models"

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#141]
We need to finalize a migration to the data project, because IJabbrRepository contains definitions that rely on JabbR_Core.Models, and if you try to change them a lot of things are impacted. I can't do it yet because this should occur after the changes @jcocchi makes on the persisted repository and with the schema name changes. Once that's done we can delete the models out of the JabbR_Core project and rely solely on the ones inside JabbR_Core.Data.Models.

**Comment by JamesEarle** [comment]
This will be resolved when @jcocchi's work gets merged, try to make everything point to the Data project where possible for now.

**Comment by adamtuliper** [comment]
If this is some thing that gets resolved automatically with Justine commits, do we need an open issue for it? Also let's make sure we aren't talking view models, which should stay in web.

**Comment by JamesEarle** [comment]
@adamtuliper as per your usual advice I made an issue so we wouldn't forget about it / ignore it when the time came 😄 Justine's should push most of the project towards the `Data` project but I'm pretty sure the original Models still exist. Once it's merged there will be a lot of runtime errors from things pointing to the wrong model types or requesting the wrong model types as parameters (my Chat hub tests and InMemoryRepository functions notably), so this can be closed once Justine's is successfully merged.

**Comment by JamesEarle** [comment]
Resolved in 0.3, the JabbR_Core.Models folder doesn't exist anymore. We're now entirely dependent on JabbR_Core.Data.Models 👍
