### ISSUE TITLE
AccountController - Login

### ISSUE THREAD

**Issue by ashanhol** [MachUpskillingFY17/JabbR-Core#172]
Account controller function. 
When you create a new .net core web app and choose security, it autogenerates with identity. Look into what that does and maybe copy over Login feature to Jabbr-Core.

**Comment by KSLHacks** [comment]
Note: User.Identity.IsAuthenticated will only work with the [Authorize] attribute.

[HttpGet] login() implemented

[Complete]
Authenticated: redirects to Lobby (no need to signin)
Not Authenticated: directs to login view to enter credentials
