### ISSUE TITLE
NuGet Packages for identity and configure startup.cs options

### ISSUE THREAD

**Issue by jcocchi** [MachUpskillingFY17/JabbR-Core#173]
Configure cookie authentication
Look at a new web project for example configuration of startup class
https://docs.asp.net/en/latest/security/authentication/identity.html

**Comment by KSLHacks** [comment]
Brought over Identity Nuget, startup.cs, DI into AccountController.cs

Pending PR #186

**Comment by KSLHacks** [comment]
services.AddIdentity<ChatUser, IdentityRole>()
IdentityRole key usese <string> .. Refactoring ChatUser Key from <int> to <string>

**Comment by KSLHacks** [comment]
NuGet, Startup and AccountController DI implemented with working EF Migrations. (refactored user.Keys to user.Id)
