### ISSUE TITLE
Refactor ViewModels out of InMem Repository

### ISSUE THREAD

**Issue by jcocchi** [MachUpskillingFY17/JabbR-Core#179]
This includes refactoring out hardcoded test data

**Comment by JamesEarle** [comment]
@jcocchi Are the ViewModels dummy data we don't need anymore and can be deleted? or should they be moved elsewhere

**Comment by jcocchi** [comment]
Because the InMemoryDatabase is implemented with EF do we still need the InMemoryRepository file? We would either need to refactor it to work with the context (in addition to refactoring out the view models/ fake data) or just use the InMemoryDatabase with the PersistedRepository file since it is already configured properly

**Comment by adamtuliper** [comment]
InMem is dead.
