### ISSUE TITLE
Determine DI configuration for Chat and ChatService

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#184]
Let's talk to David about Transient, Scoped, etc. to model the same behaviour shown in JabbR (no longer need the abstraction layer between Hub and repository).

**Comment by ashanhol** [comment]
Signalr doesn't have the scoped support written yet for web sockets. 
If we implement via Long Polling, we get a new instance each time so Scoped works ok. 
If on web sockets, it'll scope the entire request time. 
The fix for now is when configuring DI for Chat.cs, we do 
AddTransient<Chat>(
 provider => {
   var repository = serviceprovider.GetService<InMemoryRepository>();
   var chatService = new ChatService(repository, ...);
   return new Chat( repository, chatService, ...);
});

**Comment by JamesEarle** [comment]
We can't use DI on a Chat hub, hubs aren't requested on the backend by SignalR, so binding a Chat instance with DI won't solve the issue of scoping regarding the repository and ChatService.

**Comment by JamesEarle** [comment]
```
public class ServicesHubActivator : IHubActivator
    {
        private readonly IServiceProvider _serviceProvider;

        public DefaultHubActivator(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public IHub Create(HubDescriptor descriptor)
        {
            if (descriptor == null)
            {
                throw new ArgumentNullException("descriptor");
            }

            if (descriptor.HubType == null)
            {
                return null;
            }

            return _serviceProvider.GetRequiredService(descriptor.HubType) as IHub;
        }
    }

```

**Comment by JamesEarle** [comment]
Got this working, but not the exact way specified. Waiting on response from David Fowler to see if the work around is alright

**Comment by adamtuliper** [comment]
Created             services.AddSingleton<IHubActivator, ServicesHubActivator>();

**Comment by adamtuliper** [comment]
var factory = provider.GetRequiredService<IServiceScopeFactory>();
var scope = factory.CreateScope();
var sp = scope.ServiceProvider;
var repository = sp.GetService<IJabbrRepository>();
var settings = sp.GetService<IOptions<ApplicationSettings>>();
var recentMessageCache = sp.GetService<IRecentMessageCache>();
var chatService = sp.GetService<IChatService>();
var processor = new ContentProviderProcessor(repository, sp.GetService<IResourceProcessor>());

//Chat is responsible for disposing the scope
//which in turn disposes all things passed in.
//Hacky but seems the only solution at this time
//as the system (at some time) disposes chat
return new Chat(repository, settings, recentMessageCache, chatService, processor, scope);

Chat.cs
        public Chat(IServiceScopeFactory factory)
        {
            _scope = factory.CreateScope();
        }

   private bool _disposed;
        protected override void Dispose(bool disposing)
        {
            if (_disposed)
                return;

```
        Console.WriteLine($"Disposing Chat hub: {GetHashCode()}");
        if (disposing)
        {
            Console.WriteLine($"Chat hub {GetHashCode()} disposing Repository {_repository.GetHashCode()}");
           // Let the DI Container handle disposing the repo
            _scope.Dispose();
        }
        _disposed = true;

        base.Dispose(disposing);
        Console.WriteLine($"Disposed Chat hub: {GetHashCode()}");
    }
```
