### ISSUE TITLE
Hiding user secrets

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#19]
connection strings and other sensitive information should be hidden. Add to the `.gitignore` file, and clean the repository history as well (using BFG)

Investigate secure storage. Needs environment variables for development. 

Check out the Secret Manager tool

**Comment by heatherbshapiro** [comment]
:shipit:

**Comment by adamtuliper** [comment]
QA/Prod environments should use env variable.
In dev, secrets shouldn't be in a config file so use this to store the connect string
https://docs.asp.net/en/latest/security/app-secrets.html?highlight=user%20secrets

Note that these values are loaded in below in a standard project, so this we will need to do this in project

public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

**Comment by JamesEarle** [comment]
See branch `james/user-secrets`

**Comment by JamesEarle** [comment]
User secrets are hidden and added to environment variables using the Secrets Manager tool. This is a command line tool.

A reference has been added in `project.json` alongside a `userSecretsId` that is a project specific key required to access secrets.

Usage of the tool:

 - Show help menu `>dotnet user-secrets -h`
 - Get list of user secrets defined `>dotnet user-secrets list`
 - Create a new user secret `>dotnet user-secrets set key=value`

**Comment by JamesEarle** [comment]
This has been added and an example reference to the Configuration API to access environment variables is included in the `Startup.cs` file. Should be good.

:shipit:

**Comment by JamesEarle** [comment]
Reopening until successful PR merge.

**Comment by gcrev93** [comment]
:shipit: 

I tested it. it works perfect
