### ISSUE TITLE
Upgrade to Dotnet 1.0.1

### ISSUE THREAD

**Issue by ashanhol** [MachUpskillingFY17/JabbR-Core#191]
1.0.1 is out and we should try upgrading

**Comment by ashanhol** [comment]
Update: whoever works on this, document your process so we can replicate. We've had a lot of dependency issues so knowing what needed to be changed where will help in the future. 

http://www.hanselman.com/blog/NETCore10IsNowReleased.aspx

**Comment by heatherbshapiro** [comment]
For entity framework core, we are currently referencing a newer alpha version (“1.1.0-alpha1-22397”). The article is asking for us to switch it to 1.0.1., should I switch it to the older version?

**Comment by adamtuliper** [comment]
I this still blocked or OK now?
