### ISSUE TITLE
Test Linux VM for Jabbr

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#193]
Spin up an Ubuntu 14 VM get SSH working, document the procedure so everyone knows locally what they need to do with SSH keys and how to configure. If its all covered in a blog post, just point there, or create your own on the experience.

**Comment by adamtuliper** [comment]
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-mac-create-ssh-keys/

**Comment by ashanhol** [comment]
How to spin up a Linux VM on Azure from Windows: 
Follow the directions [here][1] with exceptions noted below.
-I installed cygwin even though I already had git bash as I was having trouble using openssl with git. 
The instructions seem to assume you know how to spin up a VM in azure. Follow the instructions up until "Use Putty to Connect to a Linux Machine". Before you connect to the machine, [spin up an Ubuntu 14 VM in Azure][2]. When you need to include your SSH public key, copy the contents of the box from the PuTTY Key Generator where it says "Public Key for pasting into OpenSSH authorized_keys file". 
-When using PuTTY to connect, the host IP is listed under "essentials" when you click on your VM after your VM is deployed in Azure. 

NOTE: If you're familiar with this process, you can skip the CLI and just generate keys in puttygen. 

  [1]: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-ssh-from-windows/
  [2]: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-quick-create-portal/
