### ISSUE TITLE
Research Jabbr Security

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#20]
Look into exactly how existing JabbR security works, the dependencies, tables, and middleware.
Document findings on this item.

**Comment by JamesEarle** [comment]
@adamtuliper I think #84 for Security is a more fleshed out version of this issue, since we have learned a bit more about the requirements for security in JabbR. Voting to close this to remove duplicates 👍

**Comment by adamtuliper** [comment]
Security is the main task, this is a research task in that story to track the task

**Comment by adamtuliper** [comment]
We chatted with Barry, results are in the OneNote. New tasks will be created today to represent the work from that. Closing this one.
