### ISSUE TITLE
Update Readme to include DB Context configuration via user secrets

### ISSUE THREAD

**Issue by jcocchi** [MachUpskillingFY17/JabbR-Core#201]
Use `dotnet user-secrets set key value` to save the connection string to your database as an environment variable on your machine as opposed to storing it in a appsettings.json file.

Store the connection string using the CLI tool. Note: you will have to include your actual username and password.
`dotnet user-secrets set "connectionString" "Server=MYAPPNAME.database.windows.net,1433;Initial Catalog=MYCATALOG;Persist Security Info=False;User ID={plaintext user};Password={plaintext pass};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"`

Reference the Configuration API with the key you defined, and your environment variable will be referenced. 

It should look something like this:
```
            string connection = _configuration["connectionString"];
            services.AddDbContext<JabbrContext>(options => options.UseSqlServer(connection));
```

**Comment by JamesEarle** [comment]
Updated the readme on PR #206, closing this
