### ISSUE TITLE
Create standalone EF Core console app with Jabbr Schema

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#22]
Skip repository for now (ie skip IJabbrRepository), this is just a simple standalone sample app that:
1. Has model classes migrated from legacy JabbR
2. Uses .net core
3. Uses EF core
4. Has connect string
5. Is able to create database
6. Is able to add/edit/load data
7. Use LocalDB for this (specified in connect string)
Test various models. Check indexes in this app vs. the indexes created from Jabbr legacy

**Comment by jcocchi** [comment]
remove "virtual" from all collections in models

**Comment by jcocchi** [comment]
Command in the Package Manager Console to reverse engineer DB: Scaffold-DbContext "Server={SERVER NAME};Initial Catalog={DB NAME};User ID={USER ID};Password={PASSWORD];"
It will then ask for the Provider which is Microsoft.EntityFrameworkCore.SqlServer

**Comment by adamtuliper** [comment]
Curious, what's the command line dotnet.exe option for this? this seems like the powershell version.

**Comment by adamtuliper** [comment]
Lets implement (a good testing ground for another app) encryption for connection string ala task #19 Ensure credentials don't make it into repo (if appsettings or code. Its just localdb now but this ensures it doesn't accidentally get updated in the future. Feel free to add directions in a readme.MD for the test project to have directions as per what James found out in #19 to set this up.

**Comment by jcocchi** [comment]
To test this you need to:
-Set the target project to JabbR.EFTest by right clicking on the project and selecting "Set as Startup Project". 
-In the package manager console set "JabbR.EFTest" as the default project
-Run "Update-Database" in the package manager console

This should create a localdb for you with all of the proper tables. Modify Program.cs as needed to test adding in various objects then run the project.

**Comment by ashanhol** [comment]
Note: There were also a lot of warnings about discrepancies in the targeted NuGet package. Still ended up testing fine! :shipit:
