### ISSUE TITLE
Verify SignalR is using websockets not long polling

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#24]
Ensure we do/don't need to change configuration (and if its an issue in the current signalR bits)
I noticed in the sample app that long polling was being used.

**Comment by KSLHacks** [comment]
David Fowler mentioned that the current dogfood  of signalR does **NOT** support webSockets. Only longPolling is implemented in the current release.

Looking into the connection transport setup, webSockets is correctly listed as the primary choice. When signalR is implemneted for .NetCore, the config should already be preset.
**Location:**
src\JabbR-Core\wwwroot\Scripts\jquery.signalR-2.2.0-pre-140709-b104.min.js

```
if (config.transport === "auto") {
        // TODO: Support XDM with foreverFrame
        config.transport = ["webSockets", "serverSentEvents", "longPolling"];
}
```

**Comment by JamesEarle** [comment]
This issue has gotten stale. We already know SignalR is using long polling for the time being. We can look into changing this behaviour, but this issue can be closed.
