### ISSUE TITLE
Implement BanCommand.cs

### ISSUE THREAD

**Issue by ashanhol** [MachUpskillingFY17/JabbR-Core#245]

**Comment by KSLHacks** [comment]
Working in kevin/AdminCommand

**Comment by kevinleung23** [comment]
AccountController now checks if the user.IsBanned before attempting to login with credentials. If the user.IsBanned = true, View("UserBannedNotification") is returned.

**Comment by kevinleung23** [comment]
```
// Check if user.isBanned
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user.IsBanned)
                {
                    return View("UserBannedNotification");
                }
                // If not, attempt to sign in with form credientials
```

**Comment by kevinleung23** [comment]
Continue discussion in Issue #312

**Comment by kevinleung23** [comment]
Client.Caller is not recieving "targetUser is banned" notification.
Command works correctly (changes the DB) but inconsistent (sometimes takes 1-2 commands to ban targetUser)

**Comment by kevinleung23** [comment]
Implemented a IsBanned Cookie Claim in startup.cs but not sure if we should include.

**Comment by kevinleung23** [comment]
Client.Caller now receives correct notification as well as others in the room.
Command works consistent.
Decided not to implement IsBannedVerification Cookie claim since disconnecting the Target Client Connection will cause signout (unvalidates their cookie).
