### ISSUE TITLE
Amend error messages/feedback in AccountController

### ISSUE THREAD

**Issue by ashanhol** [MachUpskillingFY17/JabbR-Core#260]
Amend feedback in AccountController. For example, when creating an account there's no feedback if you run into an error in registration (such as choosing a username that already exists or putting in incorrect username/password). In addition, error messages will show up as green in some areas (look into the cshtml partials?)

**Comment by jcocchi** [comment]
Fixed the issue with the register page not displaying an error message if you tried to register with a taken username. 
`ModelState.AddModelError(string.Empty, error.Description);` had been commented out in `AddErrors()`
