### ISSUE TITLE
Add Authentication (explore Identity)

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#28]
In reference to Issue #20 regarding JabbR security.

**Comment by adamtuliper** [comment]
We'll need to meet and look at some details on this (ideally with Barry) on api auth & identity. We have several auths here - cookie (forms type) auth, oAuth, and something for api.

**Comment by JamesEarle** [comment]
Voting to close this. Issue is pretty vague, should be broken down into smaller quantifiable steps regarding adding auth to the app.

**Comment by adamtuliper** [comment]
Smaller tasks completed, closing.
