### ISSUE TITLE
Add SignalR Core Nuget Package

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#3]
Get bits running in project

**Comment by adamtuliper** [comment]
Will require attached nuget config in project. This is a basic quasi-working example
[SignalRCoreTest.zip](https://github.com/MachUpskillingFY17/JabbR-Core/files/440201/SignalRCoreTest.zip)

**Comment by KSLHacks** [comment]
'Microsoft.AspNetCore.SignalR.Server' package restore failure. Can not locate a public nuget package available in manager (both PM CLI and manager).

**Possible Alternatives:** 
+Microsoft.AspNetCore.WebSockets.Server (0.1.0)
+Microsoft.AspNetCore.WebSockets.Protocol (0.1.0)

**Comment by KSLHacks** [comment]
'Microsoft.AspNetCore.SignalR.Server' package restore failure. Can not locate a public nuget package available in manager (both PM CLI and manager).

Possible Alternatives: 
+Microsoft.AspNetCore.WebSockets.Server (0.1.0)
+Microsoft.AspNetCore.WebSockets.Protocol (0.1.0)

**Comment by adamtuliper** [comment]
See the custom nuget.config file to change the package source in the zip
Look under Solution Items in the demo project

**Comment by JamesEarle** [comment]
@adamtuliper I can't seem to find a `nuget.config` file anywhere in the zip you uploaded. It also doesn't open as a solution for me, and I have to manually add a .sln file.

**Comment by adamtuliper** [comment]
Try this (had project, not solution)
[WebApplication2.zip](https://github.com/MachUpskillingFY17/JabbR-Core/files/441754/WebApplication2.zip)

**Comment by KSLHacks** [comment]
Added signalR Nuget reference into dependencies under project.json.

**Comment by JamesEarle** [comment]
Reopening this, we can close it once the PR gets merged
