### ISSUE TITLE
Get app loading without the "R" loading screen

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#31]

**Comment by KSLHacks** [comment]
JabbR-Core now loads successfully. Able to load past the "R" loading screen. All data (invoked by hub) is hard coded inside a mock class UserData.cs. All code altered is in Chat.cs

**Comment by KSLHacks** [comment]
@adamtuliper Able to close Issue.. pending PR #37

**Comment by adamtuliper** [comment]
I think I merged this too early, fix the get/set as per notes on 
https://github.com/MachUpskillingFY17/JabbR-Core/pull/37
under a new pull request then we can close it :)

**Comment by KSLHacks** [comment]
Submitted new PR #45

**Comment by KSLHacks** [comment]
PR #45 Merged. Closing.

**Comment by ashanhol** [comment]
There was an error with merging, this fix is no longer a part of the dev branch, seems to have gotten overwritten. The signalR screen works in the hbshapiro/remove-signal-r branch. Before this can be closed we should open a new pull request to put it back in dev.

**Comment by JamesEarle** [comment]
The bug was fixed in PR #48, now successfully merged and tested.
