### ISSUE TITLE
Implement stronger password requirement and valid email address

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#32]
Verify results of #28 

I was able to enter "k" into the email field address on the register view. -- Accepted as valid
No password restrictions and security levels. "password" -- Accepted as valid

**Comment by JamesEarle** [comment]
This will be automatically implemented by the security work in #84

**Comment by KSLHacks** [comment]
@JamesEarle is correct - Closing this issue since we already have working implementation of these out of the box restrictions.
