### ISSUE TITLE
Implement injecting of Settings class into controller

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#34]
This is a temporary 'fix' to load settings instead of hard coding them in the HomeController.Index()
Note the config.zip attached with a sample project. Look for MySettings (in the appsettings.json, startup.cs, and homecontroller.cs)

1. Create a custom class to hold the settings. This may exist in the old code)
2. Read settings from config. I had a problem getting this to work previously. See attached code. I manually configure a settings class in this project, you'll want to get this working from appsettings.json. You are supposed to be able to setup a section of the file to store your custom values that get automatically read in and filled in to your object.

[Config.zip](https://github.com/MachUpskillingFY17/JabbR-Core/files/445937/Config.zip)

3. Inject into HomeController's constructor
See https://docs.asp.net/en/latest/fundamentals/configuration.html
Read from config instead of using hard coded view model (read from settings object and populate the view model from it)

**Comment by ashanhol** [comment]
Last commit by James has our settings injected into the HomeController and there it's passed into the view. We found a resource that injects services into a view with "@inject" documented here. https://docs.asp.net/en/latest/mvc/views/dependency-injection.html

@adamtuliper, should we be doing settings like a service? Or is the way we have it ok?

**Comment by JamesEarle** [comment]
Adam cleared this up. We should be using ViewModels as wrappers to any entities we are passing data from to the Views. This adds a layer of protection and filters the data that a View has access too. In pull request #35 these changes have been made, and should be the structure for any additional DI in the future. Marking this issue as done.

**Comment by adamtuliper** [comment]
Note for semantics, ViewModels I don't consider wrappers but for storing only the fields related to the view (which I never store entities in). Want to clarify as some folks have view models with entities in them, which I'm not a big fan of. I don't have a use yet for injecting items into the views, though that could eventually happen with view only data (but I'm still for populating that from the controller mostly)

**Comment by jcocchi** [comment]
:shipit:

**Comment by JamesEarle** [comment]
Closing this issue, the PR has been merged and Justine tested the results
