### ISSUE TITLE
Add EF support into project - binaries and bootstrap code only

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#4]
Note the tools section required in project.json
Copy from an existing project. See the tools section.
Will require app settings to exist already (see other task) unless you include inline connection string.
This doesn't include models.
** This is a separate task from the standalone EF core test **

**Comment by JamesEarle** [comment]
Justine and Gabby are tackling this in issues #39 and #26. I think we can close this issue.

**Comment by adamtuliper** [comment]
This is unrelated to 39, that is schema only. This was to separate getting initial config setup vs testing EF so multiple folks could get the experience and verify to get used to bits/config. It does seem a bit ambiguous since they've done both tasks as part of 26 at this point so I'll close this one.
