### ISSUE TITLE
Update .gitignore for .swp files

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#40]
Find out the source, why we have some in some commits - from the bash subsystem on windows?
update .gitignore so they dont get into repo

**Comment by JamesEarle** [comment]
Resolved in branch `james/user-secrets`, PR #38

**Comment by JamesEarle** [comment]
Deleting it changed nothing, and `dotnet restore` works fine too. Might've been auto created on some command somewhere, but shouldn't be an issue anymore.
