### ISSUE TITLE
Get basic SignalR Chat room working

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#41]
Get the bits on a default chat room working. I say default since we dont have stuff reading/writing to database yet so hard code a room value if needed from a model coming back from server.

**Comment by KSLHacks** [comment]
Created new branch KSLHacks/SignalR_Chatroom from hshapiro/remove-signal-r

**Comment by KSLHacks** [comment]
Dependent on Issue #49

**Comment by JamesEarle** [comment]
We've got this now, and this issue is outdated since we have more quantifiable SignalR tasks at hand now. Closing.
