### ISSUE TITLE
Explore current implementation of SignalR

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#5]
+ Check browser debugging tool (developer tools -> console) to figure out what signalR is attempting to do.
+ Check Fiddler to determine long poll or web sockets? (url indicated long polling).

**Comment by KSLHacks** [comment]
Connected with Issue #24 ... waiting on .AspNetCore.SignalR implementation of websockets

**Comment by JamesEarle** [comment]
I think issues like this that have less definite "finish lines" can be closed. Thoughts @adamtuliper?

**Comment by KSLHacks** [comment]
This was issue was mainly for visibility so that it doesn't get overlooked later on. Should this be backlogged or moved to a different doc perhaps? @JamesEarle  @adamtuliper

**Comment by JamesEarle** [comment]
Issues #41 and #24 both reference more specific tasks related to SignalR, so I think this can be deleted and more quantifiable tasks can be added as we go.
