### ISSUE TITLE
Create a self contained .net core release

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#51]
Using dotnet command line, create a self contained release and attach to the 0.1.0 release https://github.com/MachUpskillingFY17/JabbR-Core/releases

**Comment by JamesEarle** [comment]
Ran the `dotnet publish` command within the `/src/JabbR-Core/` directory and was provided with a publish directory. Uploaded a zip of that to the [releases page here](https://github.com/MachUpskillingFY17/JabbR-Core/releases)

**Comment by adamtuliper** [comment]
Example format to publish (when in the Jabbr-Core/src/Jabbr-Core
`dotnet publish --configuration Release  --framework netcoreapp1.0 --runtime  win7-x64 --output bin/release/publish`
