### ISSUE TITLE
Create Jabbr-Core.Data and migrate all EF into it

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#57]
Create a new project in the solution to keep out data access in a separate layer. Migrate models and EF items into it.

**Comment by ashanhol** [comment]
Moved Migrations and Models into a library in src called JabbR-Core.Data. Tested it per Justine's recommendation in #26. Ready to be tested by someone else in branch adina/JabbrCore.Data-EF.

**Comment by KSLHacks** [comment]
Updated model names and tested db connection. Committed and pushed changes.

**Comment by KSLHacks** [comment]
Will open a PR into KSLHacks/moveRepository branch and continue working on IJabberRepository using Jabbr-Core.Data library

**Comment by jcocchi** [comment]
Can we close this now that the Data project has been merged to Dev?

**Comment by KSLHacks** [comment]
I vote we close this. But we should open a new issue up since we haven't integrated EF into the core project yet.

**Comment by jcocchi** [comment]
I'm working on that in issue #100 @KSLHacks so I'll close this one now
