### ISSUE TITLE
Extra <body> tag in HTML

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#59]
Extra tag causing warning upon loading JabbR-Core homepage. No specifics on which HTML file.

![html tags](https://cloud.githubusercontent.com/assets/17578180/18325647/cfe440c4-7507-11e6-8ae9-23a7f946e293.PNG)

**Comment by KSLHacks** [comment]
Fixed path issue to in index.cshtml to "~/images/logo32.png" and "~/images/logo64.png"

**Comment by KSLHacks** [comment]
Could not find extra <body> tag in index.cshtml

**Comment by JamesEarle** [comment]
@KSLHacks I did a search through the repo and can't find anything that contains `<body>` other than the `Index.cshtml` file. Perhaps it's auto generated?

**Comment by KSLHacks** [comment]
@JamesEarle I did as well and could not find any other files. I'll look back into this once Chat.cs is completely implemented with our EF Models. A lot of variables as of right now. We'll also probably uncover this once we start changing the UI after 1.0.0 release.

**Comment by JamesEarle** [comment]
I can't recreate this issue anymore. It may have been resolved as we've been plugging in other pieces of the program. Voting to close @adamtuliper @KSLHacks

**Comment by KSLHacks** [comment]
I agree. I no longer see this issue. I searched the entire solution for html tags as well.
