### ISSUE TITLE
Exploring existing JabbR to determine Nancy routes 

### ISSUE THREAD

**Issue by ashanhol** [MachUpskillingFY17/JabbR-Core#6]
Figure out existing Nancy and WebAPI routes. Determine why WebAPI is being used and the routes that go with that. What are the Nancy URL routes?

**Comment by ashanhol** [comment]
{controller}/{action}/{id?}

**Controller**: Home 
-Action: "/" 
--Returns: index view
-Action: "/monitor" 
--Returns: monitor view
-Action: "/status" Note: Async 
--Returns: view

**Controller**: Notifications **Base**: "/notifications"
-Action: "/"
--Returns: index view
-Action: "/markasread" POST
--Returns: Json response
-Action: "/markallasread" POST
--Returns: Json response

**Controller**: Administration **Base**: "/administration"
-Action: "/"
--Returns: View
-Action: "/" POST
--Returns: View

**Controller**: Account **Base**: "/account"
-Action: "/" 
--Returns: GetProfileView(authService, user);
-Action: "/login" Both Post and Get
--Returns based on whether or not authenticated 
-Action: "/logout" POST
--Returns: Json
-Action: "/register" 
--Returns: view
-Action: "/create" POST
--Returns: view
-Action: "/unlink" POST
--Returns:  HttpStatusCode.BadRequest;
-Action: "/newpassword" POST
--Returns: GetProfileView
-Action: "/changepassword" POST
--Returns: GetProfileView
-Action: "/changeusername" POST
--Returns: GetProfileView
-Action: "/requestresetpassword"
--Returns: view
-Action: "/requestresetpassword" POST
--Returns: view
-Action: "/resetpassword/{id}" 
--Return: view
-Action: "/resetpassword/{id} POST
--Return: view

**Comment by adamtuliper** [comment]
Check out the ApiController classes (anything that inherits from it) and see why its using those vs just nancy. I think they were there.

**Comment by ashanhol** [comment]
Under the WebApi folder, two classes inherit from ApiController- MessagesController and ApiFrontPageController. 

**ApiFrontPageController** doesn't get called by JabbR itself. It only gets called if you query ~/api, and will return the formatting in which you're supposed to call the api. 

**MessagesController** is the main content of the api. It is called by JabbR when you go to download messages from a room (last option under Room Settings in the UI). 
**NOTABLE THINGS**: You don't actually need to be authenticated in order to call this if you know the room you want to download messages from. Also, it has code supporting "private rooms", but so far there's no visible way to make a room private.
