### ISSUE TITLE
Implement GetCommands() to return actual commands in chat.cs

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#60]
Attempting to sort rooms and users upon initial loading of app. Currently does not interfere with initial homepage loading success.

![sort](https://cloud.githubusercontent.com/assets/17578180/18326600/3248da5a-750c-11e6-86a7-f074bca6dce7.PNG)

```
setCommands: function (commands) {
            ui.commands = commands.sort(function(a, b) {
                return a.Name.toString().toUpperCase().localeCompare(b.Name.toString().toUpperCase());
            });
```

**Comment by adamtuliper** [comment]
This is because of the commands not returning (GetCommands) in chat.cs isn't available. @ashanhol came across this yesterday too. Changing description to match root cause.

**Comment by JamesEarle** [comment]
Is this resolved? I don't see the specified error message any more @KSLHacks @ashanhol

**Comment by KSLHacks** [comment]
Can no longer replicate issue.
