### ISSUE TITLE
Update models to add in missing properties from old Jabbr

### ISSUE THREAD

**Issue by jcocchi** [MachUpskillingFY17/JabbR-Core#67]

**Comment by JamesEarle** [comment]
what's the progress on this? It got closed and reopened. @jcocchi is this done?

**Comment by adamtuliper** [comment]
@JamesEarle it wasn't closed :)

**Comment by jcocchi** [comment]
It is mostly done, but I don't want to close this because I'm not done with the data package integration and there might be more changes. @JamesEarle

**Comment by JamesEarle** [comment]
@adamtuliper you're right, I was looking at the referenced closed issue in the history. @jcocchi sounds good! I may remove myself from this since I haven't worked on it at all. If you want help you can assign me back to it though 👍
