### ISSUE TITLE
Implement Account controller and views

### ISSUE THREAD

**Issue by heatherbshapiro** [MachUpskillingFY17/JabbR-Core#7]
#6   Determine which controllers and views should come over after we figure out the routing.

**Comment by adamtuliper** [comment]
Need to analyze what should come over and existing structure.  Adina worked on https://github.com/MachUpskillingFY17/JabbR-Core/issues/6  which will factor into this as well. Lets keep this just for existing views/controllers for now then expand.

**Comment by adamtuliper** [comment]
Ensure functionality is present for AccountController  as it related to the nancy module from v1 Jabbr - except login/auth as that relates to #84

**Comment by adamtuliper** [comment]
TODO: Need to check validation on this

**Comment by ashanhol** [comment]
Is this related to issue #28 ?
