### ISSUE TITLE
Refactor UserData.cs out of the root

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#71]
This may be part of another task (like Jabbr-Core.Data)  here just in case for visibility.
Let's add this to a determined location. Will this be an entity, loaded from an entity?

**Comment by KSLHacks** [comment]
@adamtuliper UserData.cs was a mock model to hold data before we brought over ChatUser.cs. Where does UserData.cs still exist?

**Comment by KSLHacks** [comment]
Removed from Root.
