### ISSUE TITLE
Create new Azure Web App

### ISSUE THREAD

**Issue by JamesEarle** [MachUpskillingFY17/JabbR-Core#78]
Part of uber issue #53

**Comment by adamtuliper** [comment]
Let's chat I'll have to setup in account

**Comment by JamesEarle** [comment]
I think this is probably related to Adina's work with the Linux VM right? #193, I think the Azure work can probably be broken down into a few issues (testing cross platform specifically), is this one specifically for a web app that launches the most recent production version of JabbR?

**Comment by adamtuliper** [comment]
Unrelated, the VM is for Linux testing Azure Web apps is for hosting. The Azure work I believe is broken down into several items already - one for sql, one for web app.

**Comment by KSLHacks** [comment]
@adamtuliper Do we have a team account yet so we can start creating Azure services? - Or is this on hold?

**Comment by ashanhol** [comment]
@heatherbshapiro got this working on Adam's account. 
http://jabbrcore-test.azurewebsites.net/

Closing this issue.
