### ISSUE TITLE
Implement Testing

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#86]
Xunit for EF testing
#53 (continuous integration)
Write many integration tests :)
Stress/Load testing setup

**Comment by JamesEarle** [comment]
This seems like it will have a lot of overlap with #54, could possibly delete one and merge into a single uber issue.

**Comment by JamesEarle** [comment]
Also, issue #53 is for continuous deployment, not continuous integration.

**Comment by ashanhol** [comment]
This is a duplicate issue- closing since we have the the other uber issues. :)
