### ISSUE TITLE
Investigate layering Jabbr architecture more

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#9]
Previously there was no JabbR.Services, JabbR.Library JabbR.Data etc
Do we want to re-architect this now?

Discuss with David Fowler - get his thoughts @davidfowl

**Comment by JamesEarle** [comment]
Any updates on this that matter right now?

**Comment by jcocchi** [comment]
Implemented JabbR.Data in #57 
Not sure if we want to continue to create more sub-projects or close this issue.

**Comment by JamesEarle** [comment]
@adamtuliper what's new with this? I know we have JabbR-Core, JabbR-Core.Data, JabbR-Core.Tests, and we will likely have JabbR-Core.Cordova (or JabbR-Core.Xamarin?) in the future depending on mobile client choice, but what did you have in mind for things like JabbR-Core.Services or JabbR-Core.Library? What would constitute as making this issue able to be closed?

**Comment by davidfowl** [comment]
Cordova? nah just do xamarin...
