### ISSUE TITLE
Refactor In-mem repository to be based on In-mem EF Db

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#97]
Currently, the in-memory repository works off of plain collections. Entity Framework now supports an in memory database, so we should take advantage of it. A criticism of using collections in the past is that you are testing against in-memory collections which has a different implementation than when you switch over to using EF.

**Comment by jcocchi** [comment]
Additionally, in-memory repository is currently working with old models (and will break when we get the old models refactored out of the main project and only use the .data package models). 

Some properties have changed, for example AllowedRooms in the current implementation is a collection of ChatRooms, but in the new model it is a collection of ChatRoomChatUserAlloweds.

**Comment by adamtuliper** [comment]
Dependent upon #125
